### ISSUE TITLE
tgav_ex.py questions

### ISSUE THREAD

**Issue by kdorheim** [JGCRI/stitches#1]
Hi @abigailsnyder still learning so these might be dumb 😬 please share your python wisdom!

1. How you run `tgav_ex.py`?  I've tried copying it into a jupyter notebook that works but I was wondering you've had success with `python3 tgav_ex.py` 🤷‍♀️ 
2. For the csv files that are produced do we need the index column? 
3. Have you run into any issues with the for loop? To get the code to run in the jupyter notebook I had to add another `)` before the `:` to close the `list` call not sure if this was an issue for you too 
https://github.com/JGCRI/stitches/blob/a0f6d2d68d6e5f6df652a17b98111e7e90610109/notebooks/tgav_ex.py#L113

**Comment by abigailsnyder** [comment]
1. Nope, no idea if it would work running on its own. I was running it interactively in pycharm
2. def not, I need to look up the python equivalent of `row.names = FALSE`
3. the loop ran fine so I must have deleted a parenthesis somehow before committing it; will correct

**Comment by abigailsnyder** [comment]
2 and 3 done! thanks for catching them!

**Comment by kdorheim** [comment]
Haha so I haven't figured out how to actually use pycharm other than to open up and edit a script

**Comment by kdorheim** [comment]
Was able to get working in pycharm after changing the environment see #2. 

When executing the code interactively line by line it all goes well 👏 however when I try to run the py script all at once (^R) I run into issues related to the relative paths. This might be a question for @crvernon when he turns,  what is the py best practices for stable dir pathways, something similar to using the `here` function in R. 

```  File "/Users/dorh012/anaconda3/envs/pangeo/lib/python3.7/site-packages/pandas/io/common.py", line 493, in get_handle
    f = open(path_or_buf, mode, encoding=encoding, errors=errors, newline="")
FileNotFoundError: [Errno 2] No such file or directory: 'stitches/data/created_data/CanESM5_historical_r11i1p1f1_tgav.csv'
```

**Comment by kdorheim** [comment]
@abigailsnyder regarding the previous post is that what your inline comment
`# TODO update the way we handle where things are getting saved` 
refers to?

**Comment by abigailsnyder** [comment]
partly

**Comment by abigailsnyder** [comment]
In general, I don't see `tgav_ex.py` staying in the package, even with edits. I think its contents will end up somewhere in the `module_create_archive` or whatever we call it. But the script itself is just for giving us the tgav's we need now to start drafting out other pieces @kdorheim

**Comment by kdorheim** [comment]
Ahhhh right, totally forgot about the big picture for a moment. Well for the `module_create_archive` (or whatever it is called) we will want to make sure we use some sort of stable naming/relative paths for the files

**Comment by abigailsnyder** [comment]
One million percent, yes absolutely

**Comment by crvernon** [comment]
I can address this more when I return, but using the `pkg_resources` package when fetching data stored within a package is a good way. If you want to include the data in a package you also need to add it to a `MANIFEST.in` file in the root and update your `setup` function in `setup.py`to pass in `include_package_data = True`. If referencing external files, I can help with this when I come back. Sorry doing this on my phone.
