### ISSUE TITLE
JOSS review: README

### ISSUE THREAD

**Issue by znicholls** [JGCRI/stitches#77]
A few things in the README aren't super clear as to their meaning. 

- What does "To install pre-built run the following" mean? "To install pre-built, example data run the following"?
- What does "For users that would like to generate the run the following" mean? "For users that would like to generate the full data, run the following?" 
- `stitches.generate_pkg_data` seems to also not exist, has it been re-named?

https://github.com/openjournals/joss-reviews/issues/5525

**Comment by crvernon** [comment]
This has been addressed in a PR here: https://github.com/JGCRI/stitches/pull/85

Also, `stitches.generate_pkg_data` should now be discoverable upon merge of the meta PR.

That PR will make it in with the other review changes in a meta PR shortly.  Thanks!
