### ISSUE TITLE
JOSS review: notebooks

### ISSUE THREAD

**Issue by znicholls** [JGCRI/stitches#78]
- https://github.com/JGCRI/stitches/blob/main/notebooks/stitches-quickstart.ipynb runs nicely, there are a few tweaks which could help I think:
  - explain in a bit more detail what exactly the `get_chunk_info` and `chunk_ts` functions are doing
  - show the dataframes that are being used (e.g. what does my recipes look like, archive data etc.)
  - explain how the archive data was produced in the first place (this seems fairly key and I think an example would really help)
  - variable names could be slightly clearer e.g. `data` doesn't really tell the user anything about what the variable is
  - the diagram is super nice, well done on that

- is https://github.com/JGCRI/stitches/blob/main/notebooks/full_pipeline_example.ipynb meant to be for users or is that just internal?

https://github.com/openjournals/joss-reviews/issues/5525

**Comment by znicholls** [comment]
Comments from second round of review:

- a script or docs or something that shows how CMIP data is pre-processed, particularly details that are easy to get wrong e.g. area weighting, would be very useful still I think. Yes, this pre-processing is not necessarily part of stitches but it is important to get right in order to use stitches correctly so I think more discussion of this pre-processing step would be worthwhile to give users a better chance of using stitches correctly.

- `install_package_data` seems to download all the data every time, even if data is already downloaded. Is that intended?

- I would put a link to the ESD paper in the notebook where it is mentioned (at the moment it is just referred to but no link is included)

**Comment by abigailsnyder** [comment]
> a script or docs or something that shows how CMIP data is pre-processed, particularly details that are easy to get wrong e.g. area weighting, would be very useful still I think. Yes, this pre-processing is not necessarily part of stitches but it is important to get right in order to use stitches correctly so I think more discussion of this pre-processing step would be worthwhile to give users a better chance of using stitches correctly.
- this has been added https://github.com/JGCRI/stitches/blob/main/notebooks/preparing-input-data.ipynb 

> install_package_data seems to download all the data every time, even if data is already downloaded. Is that intended?
- a note that this is the case has been added to the quickstart notebook

> I would put a link to the ESD paper in the notebook where it is mentioned (at the moment it is just referred to but no link is included)
- this has been done
