### ISSUE TITLE
JOSS review: community guidelines

### ISSUE THREAD

**Issue by znicholls** [JGCRI/stitches#79]
I think the formatting doesn't quite render correctly at https://jgcri.github.io/stitches/reference/contributing.html (some things appear in quotes when I don't think they're meant to)

Otherwise I thought these were ok, but @Zeitsperre makes lots of good suggestions in their review

https://github.com/openjournals/joss-reviews/issues/5525

**Comment by Zeitsperre** [comment]
Thanks for opening the discussion, @znicholls. I'm mostly fine with the community guidelines, but there are a few low-hanging fruits that would make the project much better, IMO.


In addition to the rendering issue that Zeb mentioned, a few suggestions:
* There are both a `CONTRIBUTING.md` and a `contributing.rst` that contain similar information. A way of synchronizing them would be to use the MyST extnsion (https://cerodell.github.io/sphinx-quickstart-guide/build/html/markdown.html).
* Having a statement on how best to report bugs or significant problems would be great.

Incidentally, merging of the information from both of the `Contributing` files would address most of my concerns around development environment setup and most of my comments around this.

My last comment concerned the Contributor Covenant contact person of contact; I've seen other versions of the Community Guidelines that include this information and others that don't; Feel free to disregard that comment from me.

**Comment by crvernon** [comment]
No problem.  We merged the two files and kept the contribution information in the docs and removed the `CONTRIBUTING.md` file from the root dir.  Thanks!  

This will go live when the meta PR comes back into main soon.  But the work was done here:  https://github.com/JGCRI/stitches/pull/84
