### ISSUE TITLE
[JOSS] Contributor Covenant

### ISSUE THREAD

**Issue by Zeitsperre** [JGCRI/stitches#97]
A very small change that would be good to have is to copy over the `Enforcement` paragraph (see [here](https://www.contributor-covenant.org/version/2/1/code_of_conduct/)) and list a contact email for reporting issues.

This will likely never need to be used, but it's good to tick all the boxes.

Ref: https://github.com/openjournals/joss-reviews/issues/5525

**Comment by abigailsnyder** [comment]
We are in the process of getting something similar in this spirit approved through our laboratory's legal team but for now this is not an option for us as written. We agree it is necessary and  it is reflected in our todo list issue https://github.com/JGCRI/stitches/issues/82#issuecomment-2045008798
